### ISSUE TITLE
Meta: Feedback from a user

### ISSUE THREAD

**Issue by crumblingstatue** [crumblingstatue/cowbump#26]
- [ ] The prompt to open file doesn't open above the program, meaning i have to alt tab to get to it to open a file
- [ ] I have no clue how to set the default windows image viewer
- [ ] I have to remember all the file extensions and hook them manually (perhaps have groups like images, videos, audio and have an "advanced" checkbox in order to assign them individually)
- [ ] you can't scroll with mousewheel (not very one hand friendly )
- [ ] I can't screenshot the menus to show you bugs (not that big a deal)
- [ ] trying to open a png will cause the error that its not assigned a viewer, even though it is, and creates a duplicate entry for png (assigning the duplicate will fix this problem and it won't happen after that)
- [ ] not sure if intended or not but right clicking on multiple images just opens a new viewer instead of changing the existing viewer "possible option in preferences?"
- [ ] How about different views that let you see if the image is tagged or not so I don't have to check it constantly or forget one. (for example one view just has a small icon on the image, another view just shows all the tags that can fit on that image)
- [ ] If you've filtered images by a tag, and then tag a bunch of images that were untagged and still showed up, tag those images something else so that they go away, you're stuck all the way at the bottom of the endless scroller and have to slowly scroll up a bit more
- [ ] the filter tag search doesn't let you type upper case, and tags are case sensitive
- [ ] some sort of auto suggest/fill so i don't accidentally make tags for ... (or just make em case insensitive?)
- [ ] some way to apply sauce to image
- [ ] jokes aside, able to add information of the original artist, link to their work, and stuff like that to also sort by artist would be amazing
- [ ] welp, first crash of testing, i was about to add 10 images to a sequence and it crashed when i right clicked the selecetd image
- [ ] ah, all preferences of file association aren't saved anywhere or after a crash they're all lost
- [ ] ah ok, so when you make a sequence, could you have all the images in the sequence except for the first image be hidden/compressed, that way you just have to click what could be the cover of the comic/sequence and not have the rest of the sequence take up space?
- [ ] and I suppose final critique is the right click image browser is pretty good, but its low res, doesn't keep the size ratio of the original image, and you can't rescale the window bigger.
